easyarm_position_controller:
  controller_list:
    - name: easyarm_position_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
#  /gazebo_ros_control:
#    pid_gains:
#      joint1:
#        p: 10
#        d: 1
#        i: 1
#        i_clamp: 1
#      joint2:
#        p: 10
#        d: 1
#        i: 1
#        i_clamp: 1
#      joint3:
#        p: 10
#        d: 1
#        i: 1
#        i_clamp: 1
#      joint4:
#        p: 10
#        d: 1
#        i: 1
#        i_clamp: 1